"""Third revision

Revision ID: 028721596428
Revises: 2ebab214ec95
Create Date: 2023-06-23 18:05:44.148632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028721596428'
down_revision = '2ebab214ec95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
