"""Second revision

Revision ID: 2ebab214ec95
Revises: 99040333a6b5
Create Date: 2023-06-23 17:54:51.773434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebab214ec95'
down_revision = '99040333a6b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
