"""Rename ota_codes to ota_code and change type to integer

Revision ID: 88087244d853
Revises: 98b9308958c7
Create Date: 2023-11-03 16:08:25.921581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88087244d853'
down_revision = '98b9308958c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_2fa', sa.Column('ota_code', sa.Integer(), nullable=True))
    op.drop_column('users_2fa', 'ota_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_2fa', sa.Column('ota_codes', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.drop_column('users_2fa', 'ota_code')
    # ### end Alembic commands ###
