"""First revision

Revision ID: 99040333a6b5
Revises: 
Create Date: 2023-06-23 17:23:56.459692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99040333a6b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'cart_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('carts', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('carts', 'product_vendor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('carts', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('carts', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_unique_constraint(None, 'carts', ['cart_id'])
    op.create_foreign_key(None, 'carts', 'vendors', ['product_vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['user_id'])
    op.alter_column('categories', 'category_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('categories', 'category_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['category_id'])
    op.alter_column('products', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'vendor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'product_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'product_images_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'product_discount',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'product_price',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'product_stock',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_unique_constraint(None, 'products', ['product_id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['category_id'])
    op.create_foreign_key(None, 'products', 'vendors', ['vendor_id'], ['vendor_id'])
    op.alter_column('purchase_items', 'purchase_item_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_items', 'purchase_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_items', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_unique_constraint(None, 'purchase_items', ['purchase_item_id'])
    op.create_foreign_key(None, 'purchase_items', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(None, 'purchase_items', 'purchases', ['purchase_id'], ['purchase_id'])
    op.alter_column('purchases', 'purchase_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchases', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchases', 'total_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('purchases', 'purchase_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_unique_constraint(None, 'purchases', ['purchase_id'])
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['user_id'])
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.alter_column('vendors', 'vendor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendors', 'vendor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendors', 'vendor_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendors', 'vendor_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_unique_constraint(None, 'vendors', ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.alter_column('vendors', 'vendor_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendors', 'vendor_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendors', 'vendor_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendors', 'vendor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'user_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'user_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='unique')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.alter_column('purchases', 'purchase_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchases', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('purchases', 'total_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchases', 'purchase_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'purchase_items', type_='unique')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.alter_column('purchase_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_items', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_items', 'purchase_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_items', 'purchase_item_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'product_stock',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'product_price',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'product_discount',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'product_images_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'product_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'vendor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'category_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'category_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.alter_column('carts', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('carts', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('carts', 'product_vendor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('carts', 'product_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('carts', 'cart_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
