"""Change user_pond_total to String type

Revision ID: a78d53f93e16
Revises: acf51b234528
Create Date: 2023-10-06 08:42:19.105903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78d53f93e16'
down_revision = 'acf51b234528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_class', 'user_pond_total', type_=sa.String(50))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_class', 'user_pond_total', type_=sa.String(50))
    # ### end Alembic commands ###
