"""Initial

Revision ID: acf51b234528
Revises: 
Create Date: 2023-08-23 06:42:07.502820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf51b234528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_2fa_user_id'), 'users_2fa', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_auth_user_id'), 'users_auth', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_class_user_id'), 'users_class', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_market_user_id'), 'users_market', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_ponds_address_pond_address_id'), 'users_ponds_address', ['pond_address_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ponds_address_pond_address_id'), table_name='users_ponds_address')
    op.drop_index(op.f('ix_users_market_user_id'), table_name='users_market')
    op.drop_index(op.f('ix_users_class_user_id'), table_name='users_class')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users_auth')
    op.drop_index(op.f('ix_users_2fa_user_id'), table_name='users_2fa')
    # ### end Alembic commands ###
